export default {
    vars: [{
        text: '品牌色相关',
        key: 'brand',
        tip: '组件主体品牌色，其余色值由品牌色衍生',
        list: [{
            text: '品牌色',
            tip: '默认态品牌色，支持渐变',
            key: '--color-brand',
            type: 'color',
        }, {
            text: '品牌渐变色',
            tip: '默认态品牌渐变色',
            key: '--color-brand-gradient',
            type: 'color',
        }, {
            text: '品牌色区块文案色',
            tip: '默认态品牌色区块文案色',
            key: '--color-brand-text',
            type: 'color',
        }, {
            text: 'hover品牌色',
            tip: 'hover态品牌色，支持渐变',
            key: '--color-brand-hover',
            type: 'color',
        }, {
            text: 'hover品牌渐变色',
            tip: 'hover态品牌渐变色',
            key: '--color-brand-hover-gradient',
            type: 'color',
        }, {
            text: 'hover品牌色区块文案色',
            tip: 'hover态品牌色区块文案色',
            key: '--color-brand-text-hover',
            type: 'color',
        }, {
            text: '品牌对比色',
            key: '--color-brand-vs',
            type: 'color',
        }, {
            text: '品牌透明度5%',
            key: '--color-brand-opacity',
            type: 'color',
        }, {
            text: '品牌透明度15%',
            key: '--color-brand-light',
            type: 'color',
        }]
    }, {
        text: '按钮相关',
        key: 'btn',
        tip: '包含品牌按钮，次要跟随按钮以及按钮尺寸相关配置',
        list: [{
            text: '主要按钮主色',
            tip: '主要按钮支持渐变色配置，背景色主色',
            key: '--btn-brand',
            type: 'color',
        }, {
            text: '主要按钮主渐变色',
            tip: '主要按钮支持渐变色配置，背景色主渐变色',
            key: '--btn-brand-gradient',
            type: 'color',
        }, {
            text: '主要按钮文案色',
            key: '--btn-brand-text',
            type: 'color',
        }, {
            text: '主要按钮hover主色',
            tip: '主要按钮hover态，背景色主色',
            key: '--btn-brand-hover',
            type: 'color',
        }, {
            text: '主要按钮hover主渐变色',
            tip: '主要按钮hover态，背景色主渐变色',
            key: '--btn-brand-gradient-hover',
            type: 'color',
        }, {
            text: '主要按钮hover文案色',
            key: '--btn-brand-text-hover',
            type: 'color',
        }, {
            text: '次要按钮默认态边框色',
            key: '--btn-border',
            type: 'color',
        }, {
            text: '次要按钮默认态背景色',
            key: '--btn-bg',
            type: 'color',
        }, {
            text: '次要按钮默认态文案色',
            key: '--btn-text',
            type: 'color',
        }, {
            text: '次要按钮hover态边框色',
            key: '--btn-border-hover',
            type: 'color',
        }, {
            text: '次要按钮hover态背景色',
            key: '--btn-bg-hover',
            type: 'color',
        }, {
            text: '次要按钮hover态文案色',
            key: '--btn-text-hover',
            type: 'color',
        }, {
            text: '常规按钮水平间距',
            key: '--btn-h-gap',
            type: 'input',
        }, {
            text: '常规按钮最小宽度',
            key: '--btn-min-width',
            type: 'input',
        }, {
            text: '常规按钮字体大小',
            key: '--btn-font-size',
            type: 'input',
        }, {
            text: '常规按钮圆角大小',
            key: '--btn-border-radius',
            type: 'input',
        }, {
            text: '小号按钮水平间距',
            key: '--btn-small-h-gap',
            type: 'input',
        }, {
            text: '小号按钮最小宽度',
            key: '--btn-small-min-width',
            type: 'input',
        }, {
            text: '小号按钮字体大小',
            key: '--btn-small-font-size',
            type: 'input',
        }, {
            text: '小号按钮圆角大小',
            key: '--btn-small-border-radius',
            type: 'input',
        }, {
            text: '大号按钮水平间距',
            key: '--btn-large-h-gap',
            type: 'input',
        }, {
            text: '大号按钮最小宽度',
            key: '--btn-large-min-width',
            type: 'input',
        }, {
            text: '大号按钮字体大小',
            key: '--btn-large-font-size',
            type: 'input',
        }, {
            text: '大号按钮圆角大小',
            key: '--btn-large-border-radius',
            type: 'input',
        }]
    }, {
        text: '操作触点+下拉框配置',
        key: 'trigger',
        tip: '操作触点尺寸颜色，展开下拉小浮层的尺寸颜色等配置',
        list: [{
            text: '常规触点垂直间距',
            key: '--input-v-gap',
            type: 'input',
        }, {
            text: '常规触点水平间距',
            key: '--input-h-gap',
            type: 'input',
        }, {
            text: '常规触点最小宽度',
            key: '--input-min-width',
            type: 'input',
        }, {
            text: '常规触点选项高度',
            key: '--input-height',
            type: 'input',
        }, {
            text: '常规触点字体大小',
            key: '--input-font-size',
            type: 'input',
        }, {
            text: '常规触点圆角大小',
            key: '--border-radius',
            type: 'input',
        }, {
            text: '小尺寸触点垂直间距',
            key: '--input-small-v-gap',
            type: 'input',
        }, {
            text: '小尺寸触点水平间距',
            key: '--input-small-h-gap',
            type: 'input',
        }, {
            text: '小尺寸触点最小宽度',
            key: '--input-small-min-width',
            type: 'input',
        }, {
            text: '小尺寸触点选项高度',
            key: '--input-small-height',
            type: 'input',
        }, {
            text: '小尺寸触点字体大小',
            key: '--input-small-font-size',
            type: 'input',
        }, {
            text: '小尺寸触点圆角大小',
            key: '--border-small-radius',
            type: 'input',
        }, {
            text: '大尺寸触点垂直间距',
            key: '--input-large-v-gap',
            type: 'input',
        }, {
            text: '大尺寸触点水平间距',
            key: '--input-large-h-gap',
            type: 'input',
        }, {
            text: '大尺寸触点最小宽度',
            key: '--input-large-min-width',
            type: 'input',
        }, {
            text: '大尺寸触点选项高度',
            key: '--input-large-height',
            type: 'input',
        }, {
            text: '大尺寸触点字体大小',
            key: '--input-large-font-size',
            type: 'input',
        }, {
            text: '大尺寸触点圆角大小',
            key: '--border-large-radius',
            type: 'input',
        }, {
            text: '触点分割线颜色',
            key: '--input-gap-border',
            type: 'color',
        }, {
            text: '触点背景色',
            key: '--bg-highlight',
            type: 'color',
        }, {
            text: '触点边框色',
            key: '--border-highlight',
            type: 'color',
        }, {
            text: '触点hover态背景色',
            key: '--bg-highlight-hover',
            type: 'color',
        }, {
            text: '触点hover态边框色',
            key: '--border-highlight-hover',
            type: 'color',
        }, {
            text: '触点激活态背景色',
            key: '--bg-highlight-active',
            type: 'color',
        }, {
            text: '触点激活态边框色',
            key: '--border-highlight-active',
            type: 'color',
        }, {
            text: '下拉框位移',
            key: '--output-offset',
            type: 'input',
        }, {
            text: '下拉框选项高度',
            key: '--output-item-height',
            type: 'input',
        }, {
            text: '常规下拉框垂直间距',
            key: '--output-v-gap',
            type: 'input',
        }, {
            text: '常规下拉框水平间距',
            key: '--output-h-gap',
            type: 'input',
        }, {
            text: '常规下拉框圆角',
            key: '--output-border-radius',
            type: 'input',
        }, {
            text: '小尺寸下拉框垂直间距',
            key: '--output-small-v-gap',
            type: 'input',
        }, {
            text: '小尺寸下拉框水平间距',
            key: '--output-small-h-gap',
            type: 'input',
        }, {
            text: '小尺寸下拉框圆角',
            key: '--output-small-border-radius',
            type: 'input',
        }, {
            text: '大尺寸下拉框垂直间距',
            key: '--output-large-v-gap',
            type: 'input',
        }, {
            text: '大尺寸下拉框水平间距',
            key: '--output-large-h-gap',
            type: 'input',
        }, {
            text: '大尺寸下拉框圆角',
            key: '--output-large-border-radius',
            type: 'input',
        }]
    }, {
        text: '其他基础设置',
        key: 'basis',
        tip: '包含默认文本设置，外链设置，辅助色设置',
        list: [{
            text: '默认文本行高',
            key: '--line-height',
            type: 'input',
        }, {
            text: '默认文本字体大小',
            key: '--font-size',
            type: 'input',
        }, {
            text: '默认文本字体颜色',
            key: '--font-color',
            type: 'color',
        }, {
            text: '默认字体列表',
            key: '--font-family',
            type: 'input',
        }, {
            text: '默认数字字体列表',
            key: '--font-number',
            type: 'input',
        }, {
            text: 'a链接默认颜色',
            key: '--anchor-font-color',
            type: 'color',
        }, {
            text: '黑底色操作栏背景色',
            tip: '黑色背景操作栏底色，如顶部导航的背景色',
            key: '--app-nav-bg',
            type: 'color',
        }, {
            text: '全局模块背景色',
            key: '--app-bg',
            type: 'color',
        }, {
            text: '灰色操作区背景色',
            key: '--color-bg',
            type: 'color',
        }, {
            text: '灰色操作区hover态背景色',
            key: '--color-bg-hover',
            type: 'color',
        }, {
            text: '灰色操作区激活态背景色',
            key: '--color-bg-active',
            type: 'color',
        }, {
            text: '边框线颜色',
            key: '--color-border',
            type: 'color',
        }, {
            text: '警告场景提示色',
            key: '--color-warn',
            type: 'color',
        }, {
            text: '故障场景提示色',
            key: '--color-red',
            type: 'color',
        }, {
            text: '通过场景提示色',
            key: '--color-green',
            type: 'color',
        }, {
            text: '强调场景提示色',
            key: '--color-blue',
            type: 'color',
        }]
    }]
}